QuiryForum/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using QuiryForum.Models;
using QuiryForum.Data;
using QuiryForum.Models.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace QuiryForum.Controllers
{
    public class HomeController : Controller
    {
        private readonly QuiryContext context;
        private readonly UserManager<ApplicationUser> userManager;

        public HomeController(QuiryContext context, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index(int? id)
        {
            HomePageVM vm = new HomePageVM();
            vm.categories = await CategoryDB.GetAllCategories(context);
            if (id != null)
            {
                Category c = await CategoryDB.GetCategoryByID((int)id, context);
                
                vm.questions = await QuestionDB.GetQuestionsByCategory((int)id, context);
                ViewData["CategoryTitle"] = c.CategoryName;
                return View(vm);
            }
            
            vm.questions = await QuestionDB.GetAllQuestions(context);
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Index(HomePageVM vm)
        {
            if (ModelState.IsValid)
            {
                Question q = vm.q;
                ApplicationUser user = await userManager.GetUserAsync(HttpContext.User);
                q.CategoryName = await CategoryDB.GetCategoryNameByID(q.CategoryID, context);
                q.AddUser(user);
                await QuestionDB.AddAsync(q, context);

                return RedirectToAction("Index");
            };
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

QuiryForum/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using QuiryForum.Data;
using QuiryForum.Models;
using QuiryForum.Models.ViewModels;


namespace QuiryForum.Controllers
{
    public class PostsController : Controller
    {
        private readonly QuiryContext context;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signIn;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="context"></param>
        /// <param name="userManager"></param>
        /// <param name="signIn"></param>
        public PostsController(QuiryContext context, 
            UserManager<ApplicationUser> userManager, 
            SignInManager<ApplicationUser> signIn)
        {
            this.context = context;
            this.userManager = userManager;
            this.signIn = signIn;
        }

        /// <summary>
        /// Shows a list of all questions in the database with most recent at the top
        /// </summary>
        /// <returns></returns>
         public async Task<IActionResult> Index() 
         {
             List<Question> allQuestions = await QuestionDB.GetAllQuestions(context);

             return View(allQuestions);
         }

        /// <summary>
        /// Views a single question with all of its answers.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> ViewQuestion(int id)
        {
            Question q = await QuestionDB.GetQuestionByID(id, context);
            var qAndA = new ViewQuestionVM()
            {
                Question = q,
                Answers = await AnswerDB.GetAnswersToQuestion(q.QuestionID, context),
                NewAnswer = new Answer()
                {
                    QuestionID = q.QuestionID
                }
            };
            return View(qAndA);
        }

        /// <summary>
        /// Accepts an answer to the question on the page and returns the same page with 
        /// the new answer appended to the bottom.
        /// </summary>
        /// <param name="qAndA"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> ViewQuestion(ViewQuestionVM qAndA)
        {
            Answer a = qAndA.NewAnswer;
            if (ModelState.IsValid)
            {
                ApplicationUser user = await userManager.GetUserAsync(HttpContext.User);
                a.AddUser(user);
                await AnswerDB.AddAsync(a, context);
            }
            else
            {
                ViewData["ErrorMsg"] = "Sorry! we couldn't post your reply :( Maybe you didn't enter anything?";
            }
            return RedirectToAction("ViewQuestion", new { id = a.QuestionID });
        }

        /// <summary>
        /// Prompts the user to ask a new question and choose ethe category it belongs to
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Ask()
        {
            var askvm = new AskQuestionVM()
            {
                allCategories = await CategoryDB.GetAllCategories(context),
                Question = new Question()
            };

            return View(askvm);
        }

        /// <summary>
        /// Takes a new question, adds it to the database and returns to the question index page.
        /// </summary>
        /// <param name="vm"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Ask(AskQuestionVM vm)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = await userManager.GetUserAsync(HttpContext.User);
                Question q = vm.Question;
                q.AddUser(user);
                //Category c = await CategoryDB.GetCategoryByID(q.CategoryID, context);
                
                await QuestionDB.AddAsync(q, context);
                
                return RedirectToAction("Index");
            };

            return View();
        }
    }
}

QuiryForum/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<div class="row">
    <p>
        Nice picture with words overlayed <br /> "CONTACT US" <br />
        "Fill out the form below to shoot us an email."<br />
        "Old-fashioned phone calls work too."<br />
        "111-111-1111"
    </p>
</div>

<div class="row">
    <p>
        FORM FOR CONTACTING<br />
        Ask for first and last name, email, phone (optional) (checkbox for contacting by phone rather than email)<br />
        first and last name must match what we have on file for the given email (so someone does not spam someones
        email that is not theirs).<br /> an area for them to explain why they are contacting us
    </p>
</div>


<style>
    .row {
        height: 300px;
        border: dashed black .2em;
        margin-bottom: .2em;
    }

    p {
        margin: auto;
        text-align: center;
    }
</style>

QuiryForum/Views/Home/Index.cshtml
@model QuiryForum.Models.ViewModels.HomePageVM
@using QuiryForum.Data;

@{
    ViewData["Title"] = "Home";
    if (ViewData["CategoryTitle"] == null)
    {
        ViewData["CategoryTitle"] = "Recently Asked";
    }

}
<div class="row">
    <div class="col-8" id="main-content">
        <h1>@ViewData["CategoryTitle"]</h1>
        <hr />
        <div class="row">
            @foreach (Question q in Model.questions)
            {
                Category c = Model.categories.Find(x => x.CategoryID == q.CategoryID);
                <div class="card w-100 mb-2">
                        <div class="container-fluid h-100">
                            <div class="row h-100">
                                <div id="num-likes-col" class="col-1 m-0">
                                    <div class="row align-items-center h-50">
                                        <p class="mb-0" style="color:@c.Color">455</p>
                                    </div>
                                    <div class="row h-50" style="color:@c.Color">
                                        <i id="thumbs-up-icon" class="m-auto fas fa-thumbs-up"></i>
                                    </div>
                                </div>
                                <div class="col">
                                    <div id="question-user-info" class="row pb-3 mt-1">
                                        <div class="col-auto pr-0">
                                            <i id="thumbs-up-icon" class="@c.Icon" style="color:@c.Color"></i>
                                        </div>
                                        <div class="col-auto pr-1">
                                            <span style="color:@c.Color">@c.CategoryName</span>
                                        </div>
                                        <div id="username-col" class="col-auto pt-1 pl-0">
                                            <p class="text-muted">Quiry by @Html.DisplayFor(m => q.PostedBy)</p>
                                        </div>
                                        <div class="col pt-1">
                                            <p id="post-date" class="float-right text-muted">@q.FormattedDate()</p>
                                        </div>
                                    </div>

                                    <div id="question-title" class="row ml-2 mr-2">
                                        <h5 class="card-title">@Html.DisplayFor(m => q.Title)</h5>
                                    </div>
                                    <div id="question-content" class="row pb-3 ml-2 mr-2 text-muted">
                                        <p class="card-text ml-0">@Html.DisplayFor(m => q.Content)</p>
                                    </div>
                                    <div class="row m-0">
                                        <span id="num-comments" class="text-muted">0 comments</span>
                                    </div>
                                    <a class="stretched-link" asp-action="ViewQuestion" asp-controller="Posts" asp-route-id="@q.QuestionID"></a>
                                </div>
                            </div>
                        </div>
                    </div>
            }
        </div>
    </div>

    <div class="col">
        <div class="row bg-light rounded-pill" id="question-box" style="height:350px">
            <div class="col">
                <div class="row text-center">
                    <p>Ask a question!</p>
                </div>
                <div class="row">
                    <div class="form-group">
                        <input asp-for="q.Title" class="form-control h" />
                        <span asp-validation-for="q.Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <input type="button" class="btn btn-info" value="Ask!" onclick="location.href='@Url.Action("Ask", "Posts")'" />
                </div>
            </div>
        </div>

        <div class="row" id="category-container" style="border:dashed purple .2em; height:500px">
            <p>List of categories for users to browse questions</p>
        </div>
    </div>
</div>

<style>
    #num-likes-col{
        background-color:#f2f2f2;
    }
    p {
        margin: auto;
    }
    #post-date-col, #username-col{
        font-size: .85em;
    }
    #post-date, #num-comments{
        font-size: .8em;
    }
</style>